apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h1sv9jb1m-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/h1sv9jb1m-java-quarkus-gitops